
resources:
- name: example-network
  type: compute.v1.network
  properties:
    autoCreateSubnetworks: false

- name: subnet-1
  type: compute.v1.subnetwork
  properties:
    region: us-central1
    network : $(ref.example-network.selfLink)
    ipCidrRange: "192.168.0.0/20"

- name: firewall-rule-rdp
  type: compute.v1.firewall
  properties:
    network: $(ref.lab-network.selfLink)
    sourceRanges: ["0.0.0.0/0"]
    targetTags: [rdp-server ]
    allowed:
    - IPProtocol: TCP
      ports: ["3389"]

- name: firewall-rule-ssh
  type: compute.v1.firewall
  properties:
    network: $(ref.example-network.selfLink)
    sourceRanges: ["0.0.0.0/0"]
    targetTags: [ssh-server ]
    allowed:
    - IPProtocol: TCP
      ports: ["22"]  

- name: linux-vm
  type: compute.v1.instance
  properties:
    zone: us-central1-f
    machineType: zones/us-central1-f/machineTypes/f1-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-9
    networkInterfaces:
    - subnetwork: $(ref.subnet-1.selfLink)
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
        - ssh-server
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash 

- name: windows-vm
  type: compute.v1.instance
  properties:
    zone: us-central1-f
    machineType: zones/us-central1-f/machineTypes/n1-standard-4
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/windows-cloud/global/images/family/windows-2016
    networkInterfaces:
    - subnetwork: $(ref.subnet-1.selfLink)
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
        - rdp-server
    metadata:
      items:
      - key: windows-startup-script-ps1
        value: |
          # powershell
